language: groovy
jdk:
- oraclejdk7
deploy:
  provider: releases
  api_key:
    secure: dljyo+cpdZvA0mSMBEGt+b6Uli+dCT/XBwbG78hM7IK8YavPkl8svBdIT+DVulDnOLyGb/kZ3qZmV34Ty57tvuEAFdxXUWt4gJbtalGuebZ6qcMDH45GHbLg470sKIma2AoNbbEI+j+8LY3702v7Ojip/Um0BdKIIIzCxBFlX5xyi4XgcSAY7ub5IMfFKe1qpqpKs91+hs147OnOEqghiaVfEVc34gD8uWieFUQdGDVG4/OxA6S/3mam57/KaXWp4uRjJki0qV0kayYmAHkmtRVR58/I8RbG/OjuZImTtdugMAFjD25UUh7XFZo36Jaor+IUbdiWa5Os0vLltFgD/TGPrnn63gKDtG/GJVA+2bP6b7i3L8YjCEhQpVwatDXT9tGW2bhHEWVZ4D7V1qoxTGSsgAX9s5qFOgxd6rsUbf0AkIud/tMsmrcOPjxw3aOH+a89hUpOiAp+dty+PetISeGWB8qPmVsO+dN92QassCK0JtOYUPldoakg2QRmlZSBfL9nAbLR6eIoVYPmj/wH6Mwey5DwPekvKmPf0ePTzXSZmuc62ryRVG8RXNFTOcmUiVm6CcrhhuBaOA5hTkNpHhMJOsXB9wJ81aQ4ltnZPkLjD+kLVkOsMKw4M8Oskp+h3rIPuI1KD+qrqb6rmb/aLjlBvrWheql8tbNMXvD8fcA=
  file_glob: true
  file: build/libs/*.jar
  on:
    tags: true
    repo: delphyne/gradle-serviceloader-manifest
